### ISSUE TITLE
String concatenation failing with bytes

### ISSUE THREAD

**Issue by Ran-Mewo** [unimined/JvmDowngrader#1]
Info: It's attempting to downgrade Java 21 into Java 8

String concatenating bytes turns something like
```java
public static String toString(byte level, int x, int z) { 
    return level + "*" + x + "," + z;
}
```
into
```java
public static String toString(byte level, int x, int z) {
    return jvmdowngrader$concat(level, x, z);
}

private static String jvmdowngrader$concat(byte var0, int var1, int var2) {
    return new StringBuilder().append(var0).append("*").append(var1).append(",").append(var2).toString();
}
```

This looks fine until you look at the bytecode
```java
INVOKEVIRTUAL java/lang/StringBuilder.append (B)Ljava/lang/StringBuilder;
```
`StringBuilder.append(byte)` doesn't exist...
and so it gives an error of `java.lang.NoSuchMethodError: 'java.lang.StringBuilder java.lang.StringBuilder.append(byte)'`

**Comment by wagyourtail** [comment]
:sunglasses: 
![image](https://github.com/unimined/JvmDowngrader/assets/6234704/03e3193e-bc75-415b-92c6-2bd4a2b3fc46
