### ISSUE TITLE
Wrong stub for `ThreadLocalRandom.current().nextInt(int)`

### ISSUE THREAD

**Issue by Ran-Mewo** [unimined/JvmDowngrader#16]
Info: Downgrading from Java 22 to Java 8

```java
ThreadLocalRandom.current().nextInt(i)
```
turns into
```java
J_U_R_RandomGenerator.nextInt(ThreadLocalRandom.current(), i);
```
The expected behavior should be to create a `nextInt` stub in `J_U_Random` and use that instead, like
```java
J_U_Random.nextInt(ThreadLocalRandom.current(), i);
```

At the moment, it results in a `java.lang.IncompatibleClassChangeError: Method 'int xyz.wagyourtail.jvmdg.j17.stub.java_base.J_U_R_RandomGenerator.nextInt(java.lang.Object, int)' must be InterfaceMethodref constant`

**Comment by Geolykt** [comment]
Why is it altering the call anyways? `ThreadLocalRandom#nextInt(I)I` does exist in Java 8, see: <https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ThreadLocalRandom.html#nextInt-int->.

**Comment by wagyourtail** [comment]
I've fixed the actual issue in an upcoming release, tho it'll still do the useless stub, which I'll look into fixing.
