### ISSUE TITLE
NoClassDefFound inside downgraded jar

### ISSUE THREAD

**Issue by lebedynskyi** [unimined/JvmDowngrader#4]
I 've used console comand like:

` java -jar jvmdowngrader-0.7.1-all.jar -c 52 downgrade -t vineflower-1.10.1.jar vineflower-1.10.1-down.jar`

And after build in prod project with dowgraded jar i see next error in first class (Library enter)
```
java.lang.NoClassDefFoundError: Failed resolution of: Lxyz/wagyourtail/jvmdg/j9/stub/java_base/J_U_Map;
	at org.jetbrains.java.decompiler.main.decompiler.ConsoleDecompiler.<clinit>(ConsoleDecompiler.java:29)
	...
```

Inside downgraded class I see these imports:
```
import xyz.wagyourtail.jvmdg.j11.NestHost;
import xyz.wagyourtail.jvmdg.j11.NestMembers;
import xyz.wagyourtail.jvmdg.j9.stub.java_base.J_U_Map;
```

IDE does not see its implementation. Do you think I should add some additional library jar to the project?

**Comment by Geolykt** [comment]
You might be missing <https://maven.wagyourtail.xyz/releases/xyz/wagyourtail/jvmdowngrader/jvmdowngrader-java-api/0.7.1/jvmdowngrader-java-api-0.7.1-downgraded-8.jar> or similar at runtime

**Comment by lebedynskyi** [comment]
> You might be missing https://maven.wagyourtail.xyz/releases/xyz/wagyourtail/jvmdowngrader/jvmdowngrader-java-api/0.7.1/jvmdowngrader-java-api-0.7.1-downgraded-8.jar or similar at runtime

Now it compiles. Thanks.. Didn't noticed this in docs.. Anyway thanks.

**Comment by wagyourtail** [comment]
Yeah. It's either that or using [the shade method in the docs.](https://github.com/unimined/JvmDowngrader?tab=readme-ov-file#shading-api)
