### ISSUE TITLE
How far can I downgrade?

### ISSUE THREAD

**Issue by andrew121410** [unimined/JvmDowngrader#5]
Can I downgrade my Java 21 application to Java 1.4?

Is Java 8 the limit? Java 7??

**Comment by wagyourtail** [comment]
Currently the limit is java 8. Tho java 7 is planned. going any lower would be very difficult.

**Comment by andrew121410** [comment]
Thank you for the work on this ❤️ I came from https://github.com/RaphiMC/JavaDowngrader which was deprecated for this.

**Comment by wagyourtail** [comment]
i realized i didnt confirm the upper limit. Its Java 22. I updated to include this information in the readme
